// Fontes RTL do SMMA (relativas a raiz). Usado por sim/run_xcelium.sh.
RTL/aritmetica/Divider_Q15.v
RTL/aritmetica/FP_Arith_Unit.v
RTL/aritmetica/FP_Mult_Unit.v
RTL/barramento/Data_Bus_Driver.v
RTL/barramento/Stream_Fork.v
RTL/cnn/CNN_Control_FSM.v
RTL/cnn/CNN_Conv_Layer.v
RTL/cnn/CNN_Dense_Classifier.v
RTL/cnn/CNN_Line_Buffer.v
RTL/cnn/CNN_MAC_Unit.v
RTL/cnn/CNN_MaxPool.v
RTL/cnn/CNN_ReLU.v
RTL/cnn/CNN_Top.v
RTL/cnn/CNN_Weight_ROM.v
RTL/cnn/FFT_Log2_Compress.v
RTL/cnn/Spectrogram_Buffer.v
RTL/entrada/FIR_Decimator.v
RTL/entrada/Sample_Source.v
RTL/fft/FFT_Addr_Gen.v
RTL/fft/FFT_Bit_Reverse.v
RTL/fft/FFT_Butterfly.v
RTL/fft/FFT_Control_FSM.v
RTL/fft/FFT_Magnitude.v
RTL/fft/FFT_Memory.v
RTL/fft/FFT_Top.v
RTL/fft/FFT_Twiddle_ROM.v
RTL/lms/LMS_Accumulator_Error_Scale.v
RTL/lms/LMS_Control_FSM.v
RTL/lms/LMS_Filter_Top.v
RTL/lms/LMS_Input_Delay_Line.v
RTL/lms/LMS_Processing_Element.v
RTL/lms/LMS_Stage.v
RTL/lms/LMS_Weight_Storage.v
RTL/matriz/Yule_Walker_Solver.v
RTL/matriz/autocorrelacao_yw.v
RTL/matriz/fixed_point_divider.v
RTL/matriz/gauss_jordan_inv.v
RTL/mdc/f0_estimator.v
RTL/mdc/mdc_gcd.v
RTL/mdc/peak_detector.v
RTL/memorias/Frame_Builder.v
RTL/memorias/Spectrum_Accumulator.v
RTL/ml/Feature_Spectral.v
RTL/ml/ML_Tree_Classifier.v
RTL/ml/Parameter_RegFile.v
RTL/top/SMMA_Global_Control.v
RTL/top/SMMA_Panel.v
RTL/top/SMMA_Top.v
